### PR TITLE
menu changes

### PR DESCRIPTION
**Pull request by tomquinn04**

### CODE REVIEW

**Comment by tomquinn04** [comment]
this fix for NULL might not work - @dkgroot is checking on this

**Comment by tomquinn04** [comment]
"NULL"/NULL discrepancy fixed in develop branch by dkgroot, leaving only menu changes to be done.

**Review by steve-lad — CHANGES_REQUESTED** [review]
At this time, it is preferable to regroup all SCCP settings in one easy place, so do not change the category.
The menu item changes are a good idea, but please remove the SCCP as this is implicit given that the menu location does not change
Remove the NULL/NULL PR from this request. These are Director settings and have already been changed so this is no longer applicable

**Comment by tomquinn04** [comment]
Starting this PR from a fresh fork because I don't know how to github 🙄

**Pull request closed without merging**
