### PR TITLE
Update phonecodepage conversion list

### PR DESCRIPTION
**Pull request by dkgroot**
Extended the list of codepage conversions

### CODE REVIEW

**Comment by steve-lad** [comment]
Thanks Diederik. 

Unfortunately, PHP Switch statements only accept single arguments and not arrays. To achieve what you want to do, you need to run multiple cases: without any break so that they all fall through to the desired result.

Extconfigs language array is no longer used although it is not an issue to update it. The data that needs to be updated is in the head of XMLInterface.class which is in a different format.

Please could you look at these changes in your PR

**Comment by dkgroot** [comment]
I knew cisco_language array was no longer used, but i liked it more than the switch/case + if solution. So you can decide where to take this. Maybe integrate the three locations into one table or something. Little note. I am not 100% sure if all the codepages choossen are the correct ones, but they were the ones that made sense. It was based on the 'guess codepage' tool run against the tag_file in the Locale Directory. I had to fixup a couple of them, for example arabic/turkisch were reversed. So consider it best effort and we will hopefully get some complaint some time in the future where they do not match 100%

**Comment by steve-lad** [comment]
Committed to 16

**Review by steve-lad — COMMENTED** [review]
Thanks Diederik

**Pull request closed without merging**
